name: Build

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  all:
    name: All

    strategy:
      matrix:
        browser:
        - chrome
        - firefox
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        exclude:
        - os: windows-latest
          browser: firefox

    runs-on: ${{matrix.os}}

    steps:

    - uses: actions/checkout@v2

    - name: Install Main Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        components: clippy
        override: true

    - name: Versions
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Clippy
      run: cargo clippy

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Test WASM
      run: wasm-pack test --headless --${{ matrix.browser }}
